name: Publish MATLAB binaries

on: 
  release: 
    types: [published]

env:
  BUILD_FOLDER: build
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/ezc3d
          - os: macos-latest
            label: osx-64
            prefix: /Users/runner/miniconda3/envs/ezc3d
          - os: windows-latest
            label: win-64
            prefix: C:\Miniconda3\envs\ezc3d
          - version: [R2021b, R2022a, R2022b, R2023a, R2023b, R2024a]
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
        
      - name: Print mamba info
        run: | 
          mamba info
          mamba list
          
      - name: Install dependencies
        run: | 
          mamba install cmake git pkgconfig -cconda-forge
          mamba list
          git submodule update --init --recursive

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.version }}

      - name: Build ezc3d
        run: |
          MAIN_FOLDER=`pwd`
          cd
          HOME=`pwd`
          cd $MAIN_FOLDER
          CONDA_ENV_PATH=$CONDA/envs/ezc3d
          mkdir -p $MAIN_FOLDER/$BUILD_FOLDER
          cd $MAIN_FOLDER/$BUILD_FOLDER
          cmake -DCMAKE_INSTALL_PREFIX=$CONDA_ENV_PATH -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=ON -DBUILD_DOC=OFF -DBUILD_EXAMPLE=OFF -DUSE_MATRIX_FAST_ACCESSOR=OFF -DBINDER_MATLAB=ON -DMatlab_ezc3d_INSTALL_DIR=$HOME -DBINDER_PYTHON3=OFF ..
          make install -j${{ steps.cpu-cores.outputs.count }}
          cd $MAIN_FOLDER

      - name: Build MATLAB archives
        run: |
          zip -r ezc3d_matlab.zip $HOME/ezc3d_matlab

      - name: Upload files to a GitHub release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "ezc3d_matlab_${{ matrix.label }}_${{ matrix.version }}.zip"
          update_latest_release: true
          verbose: true
          overwrite: true